=== clarin-eric/FAIRCORE4EOSC-T4.5/Schema/Dataverse/demo-10.5072-FK2-PPORT-generated-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "id": {"type": "number"},
        "identifier": {"type": "string"},
        "persistentUrl": {"type": "string"},
        "protocol": {"type": "string"},
        "authority": {"type": "string"},
        "publisher": {"type": "string"},
        "publicationDate": {"type": "string"},
        "storageIdentifier": {"type": "string"},
        "datasetVersion": {"$ref": "#/definitions/datasetVersion_type"}
    },
    "definitions": {
        "license_type": {
            "type": "object",
            "properties": {
                "name": {"type": "string"},
                "uri": {"type": "string"},
                "iconUri": {"type": "string"}
            }
        },
        "fields_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "typeName": {"type": "string"},
                    "multiple": {"type": "boolean"},
                    "typeClass": {"type": "string"},
                    "value": {"type": "string"}
                },
                "required": [
                    "typeName",
                    "multiple",
                    "typeClass",
                    "value"
                ]
            }
        },
        "citation_type": {
            "type": "object",
            "properties": {
                "displayName": {"type": "string"},
                "name": {"type": "string"},
                "fields": {"$ref": "#/definitions/fields_type"}
            }
        },
        "metadataBlocks_type": {
            "type": "object",
            "properties": {
                "citation": {"$ref": "#/definitions/citation_type"}
            }
        },
        "categories_type": {
            "type": "array",
            "minItems": 0,
            "items": {"type": "string"}
        },
        "checksum_type": {
            "type": "object",
            "properties": {
                "type": {"type": "string"},
                "value": {"type": "string"}
            }
        },
        "dataFile_type": {
            "type": "object",
            "properties": {
                "id": {"type": "number"},
                "persistentId": {"type": "string"},
                "filename": {"type": "string"},
                "contentType": {"type": "string"},
                "filesize": {"type": "number"},
                "categories": {"$ref": "#/definitions/categories_type"},
                "storageIdentifier": {"type": "string"},
                "rootDataFileId": {"type": "number"},
                "md5": {"type": "string"},
                "checksum": {"$ref": "#/definitions/checksum_type"},
                "creationDate": {"type": "string"},
                "originalFileFormat": {"type": "string"},
                "originalFormatLabel": {"type": "string"},
                "originalFileSize": {"type": "number"},
                "originalFileName": {"type": "string"},
                "UNF": {"type": "string"}
            }
        },
        "files_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "label": {"type": "string"},
                    "restricted": {"type": "boolean"},
                    "version": {"type": "number"},
                    "datasetVersionId": {"type": "number"},
                    "categories": {"$ref": "#/definitions/categories_type"},
                    "dataFile": {"$ref": "#/definitions/dataFile_type"}
                },
                "required": [
                    "restricted",
                    "dataFile",
                    "label",
                    "version",
                    "datasetVersionId"
                ]
            }
        },
        "datasetVersion_type": {
            "type": "object",
            "properties": {
                "id": {"type": "number"},
                "datasetId": {"type": "number"},
                "datasetPersistentId": {"type": "string"},
                "storageIdentifier": {"type": "string"},
                "versionNumber": {"type": "number"},
                "versionMinorNumber": {"type": "number"},
                "versionState": {"type": "string"},
                "lastUpdateTime": {"type": "string"},
                "releaseTime": {"type": "string"},
                "createTime": {"type": "string"},
                "publicationDate": {"type": "string"},
                "citationDate": {"type": "string"},
                "license": {"$ref": "#/definitions/license_type"},
                "termsOfAccess": {"type": "string"},
                "fileAccessRequest": {"type": "boolean"},
                "metadataBlocks": {"$ref": "#/definitions/metadataBlocks_type"},
                "files": {"$ref": "#/definitions/files_type"},
                "citation": {"type": "string"}
            }
        }
    }
}

=== clarin-eric/FAIRCORE4EOSC-T4.5/Schema/Dataverse/demo-10.5072-FK2-PPORT.json
{"id":19,"identifier":"FK2/PPPORT","persistentUrl":"https://doi.org/10.5072/FK2/PPPORT","protocol":"doi","authority":"10.5072","publisher":"Demo Dataverse","publicationDate":"2015-04-20","storageIdentifier":"file://10.5072/FK2/PPPORT","datasetVersion":{"id":12,"datasetId":19,"datasetPersistentId":"doi:10.5072/FK2/PPPORT","storageIdentifier":"file://10.5072/FK2/PPPORT","versionNumber":2,"versionMinorNumber":0,"versionState":"RELEASED","lastUpdateTime":"2017-08-31T09:24:19Z","releaseTime":"2017-08-31T09:24:19Z","createTime":"2015-04-20T14:14:02Z","publicationDate":"2015-04-20","citationDate":"2015-04-20","license":{"name":"CC0 1.0","uri":"http://creativecommons.org/publicdomain/zero/1.0","iconUri":"https://licensebuttons.net/p/zero/1.0/88x31.png"},"termsOfAccess":"You need to request for access. ","fileAccessRequest":true,"metadataBlocks":{"citation":{"displayName":"Citation Metadata","name":"citation","fields":[{"typeName":"title","multiple":false,"typeClass":"primitive","value":"Reproductive Health Laws Around the World"},{"typeName":"alternativeTitle","multiple":false,"typeClass":"primitive","value":"Reproductive Health Laws"},{"typeName":"author","multiple":true,"typeClass":"compound","value":[{"authorName":{"typeName":"authorName","multiple":false,"typeClass":"primitive","value":"Finlay, Jocelyn"},"authorAffiliation":{"typeName":"authorAffiliation","multiple":false,"typeClass":"primitive","value":"Harvard University"},"authorIdentifierScheme":{"typeName":"authorIdentifierScheme","multiple":false,"typeClass":"controlledVocabulary","value":"ORCID"},"authorIdentifier":{"typeName":"authorIdentifier","multiple":false,"typeClass":"primitive","value":"1234"}}]},{"typeName":"datasetContact","multiple":true,"typeClass":"compound","value":[{"datasetContactName":{"typeName":"datasetContactName","multiple":false,"typeClass":"primitive","value":"Finlay, Jocelyn"},"datasetContactAffiliation":{"typeName":"datasetContactAffiliation","multiple":false,"typeClass":"primitive","value":"Harvard University"},"datasetContactEmail":{"typeName":"datasetContactEmail","multiple":false,"typeClass":"primitive","value":"jfinlay@hsph.harvard.edu"}}]},{"typeName":"dsDescription","multiple":true,"typeClass":"compound","value":[{"dsDescriptionValue":{"typeName":"dsDescriptionValue","multiple":false,"typeClass":"primitive","value":"A numeric representation of reproductive health laws around the world"},"dsDescriptionDate":{"typeName":"dsDescriptionDate","multiple":false,"typeClass":"primitive","value":"2015-04-20"}}]},{"typeName":"subject","multiple":true,"typeClass":"controlledVocabulary","value":["Social Sciences"]},{"typeName":"keyword","multiple":true,"typeClass":"compound","value":[{"keywordValue":{"typeName":"keywordValue","multiple":false,"typeClass":"primitive","value":"reproductive health"}},{"keywordValue":{"typeName":"keywordValue","multiple":false,"typeClass":"primitive","value":"contraception"}}]},{"typeName":"depositor","multiple":false,"typeClass":"primitive","value":"Finlay, Jocelyn"},{"typeName":"dateOfDeposit","multiple":false,"typeClass":"primitive","value":"2015-04-20"}]}},"files":[{"label":"Chrysanthemum.jpg","restricted":true,"version":1,"datasetVersionId":12,"categories":["Documentation","photo"],"dataFile":{"id":21,"persistentId":"","filename":"Chrysanthemum.jpg","contentType":"image/jpeg","filesize":879394,"categories":["Documentation","photo"],"storageIdentifier":"file://14cd70d4817-e712e6121557","rootDataFileId":-1,"md5":"076e3caed758a1c18c91a0e9cae3368f","checksum":{"type":"MD5","value":"076e3caed758a1c18c91a0e9cae3368f"},"creationDate":"2015-04-20"}},{"label":"Desert.jpg","restricted":false,"version":1,"datasetVersionId":12,"dataFile":{"id":20,"persistentId":"","filename":"Desert.jpg","contentType":"image/jpeg","filesize":845941,"storageIdentifier":"file://14cd7103d7d-a1bcea521b5f","rootDataFileId":-1,"md5":"ba45c8f60456a672e003a875e469d0eb","checksum":{"type":"MD5","value":"ba45c8f60456a672e003a875e469d0eb"},"creationDate":"2015-04-20"}},{"label":"gss.tab","restricted":false,"version":1,"datasetVersionId":12,"dataFile":{"id":28,"persistentId":"","filename":"gss.tab","contentType":"text/tab-separated-values","filesize":527005,"storageIdentifier":"file://14cd7151b89-f7ec23877f3d","originalFileFormat":"application/x-stata","originalFormatLabel":"Stata Binary","originalFileSize":527005,"originalFileName":"gss.dta","UNF":"UNF:6:YGLwUMzN0Bsa9Qe0iIc52Q==","rootDataFileId":-1,"md5":"ad0542214903e1090a957f26e83120cf","checksum":{"type":"MD5","value":"ad0542214903e1090a957f26e83120cf"},"creationDate":"2015-04-20"}}],"citation":"Finlay, Jocelyn, 2015, \"Reproductive Health Laws Around the World\", https://doi.org/10.5072/FK2/PPPORT, Demo Dataverse, V2"}}
